services:
  server:
    build: .
    ports:
      - 5001:5000
    env_file:
      - .env
    networks:
      - springapimysql-net
    environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/readerhub?allowPublicKeyRetrieval=true
        - aws.credentials.access-key-id=${AWS_ACCESS_KEY_ID}
        - aws.credentials.secret-access-key=${AWS_SECRET_ACCESS_KEY}
        - aws.bucket.region=${AWS_S3_BUCKET_REGION}
        - aws.bucket.name=${AWS_S3_BUCKET_NAME}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - 3307:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: readerhub
      MYSQL_USER: naveen
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
networks:
  springapimysql-net: